version: "2"
services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: web_container
    volumes:
      - ./bin/wait.sh:/extension/wait.sh
    environment:
      - PORT=9000
      - EXTENSION_SCRIPT=/extension/wait.sh
    links:
      - elasticsearch
    ports:
      - "9000:9000"
  neo4j:
    restart: always
    image: neo4j:3.1.4
    container_name: neo4j_container
    volumes:
      - ./neo4j/conf/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/plugins:/plugins
      - ./neo4j/data/import:/data/import
      - ./bin/wait.sh:/extension/wait.sh
    environment:
      - elasticsearch="http://elasticsearch_container"
      - NEO4J_AUTH=none
      - EXTENSION_SCRIPT=/extension/wait.sh
    ports:
      - "7473:7473"
      - "7687:7687"
      - "7474:7474"
    links:
      - elasticsearch
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    container_name: elasticsearch_container
    volumes:
      - ./elastic/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - http.host=0.0.0.0
      - neo4j="http://neo4j_container"
    ports:
      - "9200:9200"
