version: "2"
services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: web_container
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=9000

      # Source .env within docker environment
      # https://goo.gl/8m8iwk
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./app/.env
    ports:
      - "9000:9000"
  neo4j:
    restart: always
    image: neo4j:3.2.1
    container_name: neo4j_container
    volumes:
      - ./neo4j/conf:/conf/
      - ./neo4j/plugins:/plugins
      - ./neo4j/data/import:/data/import
    environment:
      - elasticsearch="http://elasticsearch_container"
      - NEO4J_AUTH=none
    ports:
      - "7473:7473"
      - "7687:7687"
      - "7474:7474"
    links:
      - elasticsearch
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch_container
    volumes:
      - ./elastic/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - http.host=0.0.0.0
      - neo4j="http://neo4j_container"
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana_container
    links:
      - elasticsearch
    ports:
      - "5601:5601"
