export const FETCH_SEARCH_SUGGESTIONS = 'FETCH_SEARCH_SUGGESTIONS';
export const RECEIVE_SEARCH_SUGGESTIONS = 'RECEIVE_SEARCH_SUGGESTIONS';
export const SELECT_SEARCH_SUGGESTION = 'SELECT_SEARCH_SUGGESTION';
export const BROWSE_SEARCH_SUGGESTION = 'BROWSE_SEARCH_SUGGESTION';
export const RECEIVE_GOOGLE_IMAGE = 'RECEIVE_GOOGLE_IMAGE';
